### ISSUE TITLE
Make a variant of ProcessOutput as easy to use as ProcessLogger

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/os-lib#19]
Congratulations for `os-lib`, very easy to use and powerful.

Many times, we work with String instead of array of Bytes, even though Bytes is more general.
[ProcessLogger](https://www.scala-lang.org/api/2.12.0/scala/sys/process/ProcessLogger$.html) is much easier to use than os-lib in this common use case.

And working with lines could be useful.

**Comment by lihaoyi-databricks** [comment]
There is now a `os.ProcessOutput.ReadLines` in master

**Comment by DavidPerezIngeniero** [comment]
Now `os-lib` covers all my needs for launching processes.
