### ISSUE TITLE
Publish scala-native build

### ISSUE THREAD

**Issue by DhashS** [lihaoyi/os-lib#22]
When i tried to build `os-lib`, with my limited understanding of mill I think I got a straightforward scala-native build out. it looks to me like os-lib depends _only_ on stuff that's in javalib in scala-native, and all it's dependencies are published already.

**Comment by mkotsbak** [comment]
Can you supply a patch in a pull request then?

**Comment by lihaoyi-databricks** [comment]
Closing for now; we can revisit this when scala native 0.4.0 is out, together with the rest of my libraries

**Comment by gryphis** [comment]
Three years later, scala-native 0.4.5 is out, but it looks the same: os-lib does not work :-(
